BEGIN;

CREATE TABLE IF NOT EXISTS scales (
    id TEXT PRIMARY KEY,
    month TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT DEFAULT 'RASCUNHO',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

COMMIT;